config {
  type: "table",
  schema: "dataform_staging",
  name: "5_check_duplicate_national_ts"
}

SELECT month,
hpi_value,
hpi_yoy_pct_chg,
hpi_distance,
hpi_returns,
hpi_real,
hpi_trend,
afford_detrended,
afford_pmt,
acceleration_value,
velocity_value,
risk,
       COUNT(*) as count
FROM ${ref('4_replace_table_national_ts')}
GROUP BY month,
hpi_value,
hpi_yoy_pct_chg,
hpi_distance,
hpi_returns,
hpi_real,
hpi_trend,
afford_detrended,
afford_pmt,
acceleration_value,
velocity_value,
risk
HAVING count > 1
