config {
  type: "table",
  schema: "dataform_staging",
  name: "6_Clean_national_ts"
}
SELECT month, hpi_value, hpi_yoy_pct_chg, hpi_distance, hpi_returns, hpi_real, hpi_trend, afford_detrended, afford_pmt, acceleration_value, velocity_value, risk
FROM (
  SELECT *, ROW_NUMBER() OVER(PARTITION BY month, hpi_value, hpi_yoy_pct_chg, hpi_distance, hpi_returns, hpi_real, hpi_trend, afford_detrended, afford_pmt, acceleration_value, velocity_value, risk ORDER BY month) AS row_number
  FROM ${ref('4_replace_table_national_ts')}
)
WHERE row_number = 1
