config {
  type: "table",
  schema: "dataform_staging",
  name: "1_column_to_delete"
}

SELECT 
  'date' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(date IS NULL) as missing_rows, 
  ROUND(COUNTIF(date IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.NT_TABLE)} 
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'country' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(country IS NULL) as missing_rows, 
  ROUND(COUNTIF(country IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'hospitalized_patients_symptoms' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(hospitalized_patients_symptoms IS NULL) as missing_rows, 
  ROUND(COUNTIF(hospitalized_patients_symptoms IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.NT_TABLE)} 
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'hospitalized_patients_intensive_care' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(hospitalized_patients_intensive_care IS NULL) as missing_rows, 
  ROUND(COUNTIF(hospitalized_patients_intensive_care IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'total_hospitalized_patients' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(total_hospitalized_patients IS NULL) as missing_rows, 
  ROUND(COUNTIF(total_hospitalized_patients IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.NT_TABLE)} 
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'home_confinement_cases' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(home_confinement_cases IS NULL) as missing_rows, 
  ROUND(COUNTIF(home_confinement_cases IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.NT_TABLE)}  
HAVING missing_percentage > 25 

UNION ALL

SELECT
   'total_current_confirmed_cases' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(total_current_confirmed_cases IS NULL) AS missing_rows,
   ROUND(COUNTIF(total_current_confirmed_cases IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'new_current_confirmed_cases' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(new_current_confirmed_cases IS NULL) AS missing_rows,
   ROUND(COUNTIF(new_current_confirmed_cases IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'new_total_confirmed_cases' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(new_total_confirmed_cases IS NULL) AS missing_rows,
   ROUND(COUNTIF(new_total_confirmed_cases IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'recovered' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(recovered IS NULL) AS missing_rows,
   ROUND(COUNTIF(recovered IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'deaths' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(deaths IS NULL) AS missing_rows,
   ROUND(COUNTIF(deaths IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'total_confirmed_cases' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(total_confirmed_cases IS NULL) AS missing_rows,
   ROUND(COUNTIF(total_confirmed_cases IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'tests_performed' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(tests_performed IS NULL) AS missing_rows,
   ROUND(COUNTIF(tests_performed IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'note' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(note IS NULL) AS missing_rows,
   ROUND(COUNTIF(note IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.NT_TABLE)}
HAVING missing_percentage >25
