config {
  type: "table",
  schema: "dataform_staging",
  name: "6_Clean"
}
SELECT date, country, hospitalized_patients_symptoms, hospitalized_patients_intensive_care, total_hospitalized_patients, home_confinement_cases, total_current_confirmed_cases, new_current_confirmed_cases, new_total_confirmed_cases, recovered, deaths, total_confirmed_cases, tests_performed
FROM (
  SELECT *, ROW_NUMBER() OVER(PARTITION BY date, country, hospitalized_patients_symptoms, hospitalized_patients_intensive_care, total_hospitalized_patients, home_confinement_cases, total_current_confirmed_cases, new_current_confirmed_cases, new_total_confirmed_cases, recovered, deaths, total_confirmed_cases, tests_performed ORDER BY date) AS row_number
  FROM ${ref('4_semi_clean')}
)
WHERE row_number = 1