config {
  type: "table",
  schema: "dataform_staging",
  name: "3_most_frequent_values_block_value_ts"
}

SELECT
  (SELECT block_id FROM (
    SELECT block_id, COUNT(*) as count FROM dataform_staging.2_semi_clean_block_value_ts WHERE block_id IS NOT NULL GROUP BY block_id ORDER BY count DESC LIMIT 1)) as block_id_most_frequent,
  (SELECT property_type FROM (
    SELECT property_type, COUNT(*) as count FROM dataform_staging.2_semi_clean_block_value_ts WHERE property_type IS NOT NULL GROUP BY property_type ORDER BY count DESC LIMIT 1)) as property_type_most_frequent,
  (SELECT month FROM (
    SELECT month, COUNT(*) as count FROM dataform_staging.2_semi_clean_block_value_ts WHERE month IS NOT NULL GROUP BY month ORDER BY count DESC LIMIT 1)) as month_most_frequent,
  (SELECT value_50 FROM (
    SELECT value_50, COUNT(*) as count FROM dataform_staging.2_semi_clean_block_value_ts WHERE value_50 IS NOT NULL GROUP BY value_50 ORDER BY count DESC LIMIT 1)) as value_50_most_frequent,
  (SELECT value_sqft_50 FROM (
    SELECT value_sqft_50, COUNT(*) as count FROM dataform_staging.2_semi_clean_block_value_ts WHERE value_sqft_50 IS NOT NULL GROUP BY value_sqft_50 ORDER BY count DESC LIMIT 1)) as value_sqft_50_most_frequent
