config {
  type: "table",
  schema: "dataform_staging",
  name: "4_replace_block_value_ts",
  tags: "requete3_4"
}

SELECT
  COALESCE(t.block_id, v.block_id_most_frequent) as block_id,
  COALESCE(t.property_type, v.property_type_most_frequent) as property_type,
  COALESCE(t.month, v.month_most_frequent) as month,
  COALESCE(t.value_50, v.value_50_most_frequent) as value_50,
  COALESCE(t.value_sqft_50, v.value_sqft_50_most_frequent) as value_sqft_50
FROM dataform_staging.2_semi_clean_block_value_ts t
CROSS JOIN ${ref('3_most_frequent_values_block_value_ts')} v
