config {
  type: "table",
  schema: "dataform_staging",
  name: "6_Clean_Block_rental_value",
  tags: "requete1_6"
}
SELECT block_id, fips, zip, msa, state, lat, lon, property_type, value_5, value_25, value_50, value_75, value_95, value_count, value_max, value_min, value_average, value_sd, value_sqft_5, value_sqft_25, value_sqft_50, value_sqft_75, value_sqft_95, value_sqft_count, value_sqft_max, value_sqft_min, value_sqft_average, value_sqft_sd
FROM (
  SELECT *, ROW_NUMBER() OVER(PARTITION BY block_id, fips, zip, msa, state, lat, lon, property_type, value_5, value_25, value_50, value_75, value_95, value_count, value_max, value_min, value_average, value_sd, value_sqft_5, value_sqft_25, value_sqft_50, value_sqft_75, value_sqft_95, value_sqft_count, value_sqft_max, value_sqft_min, value_sqft_average, value_sqft_sd ORDER BY block_id) AS row_number
  FROM ${ref('4_replace_table_Block_rental_value')}
)
WHERE row_number = 1
