config {
  type: "table",
  schema: "dataform_staging",
  name: "1_Delete column_msa_cs.sqlx"
}

SELECT 
  'msa' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(msa IS NULL) as missing_rows, 
  ROUND(COUNTIF(msa IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.MS_TABLE)} 
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'name' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(name IS NULL) as missing_rows, 
  ROUND(COUNTIF(name IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'state' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(state IS NULL) as missing_rows, 
  ROUND(COUNTIF(state IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.MS_TABLE)} 
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'cagr' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(cagr IS NULL) as missing_rows, 
  ROUND(COUNTIF(cagr IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'cagr_zscore' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(cagr_zscore IS NULL) as missing_rows, 
  ROUND(COUNTIF(cagr_zscore IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.MS_TABLE)} 
HAVING missing_percentage > 25 

UNION ALL

SELECT 
  'cagr_1' as columnname, 
  COUNT(*) as total_rows, 
  COUNTIF(cagr_1 IS NULL) as missing_rows, 
  ROUND(COUNTIF(cagr_1 IS NULL)*100/COUNT(*),2) as missing_percentage 
FROM ${ref(constants.MS_TABLE)}  
HAVING missing_percentage > 25 

UNION ALL

SELECT
   'cagr_1_zscore' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(cagr_1_zscore IS NULL) AS missing_rows,
   ROUND(COUNTIF(cagr_1_zscore IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'cagr_1' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(cagr_1 IS NULL) AS missing_rows,
   ROUND(COUNTIF(cagr_1 IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'cagr_5_zscore' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(cagr_5_zscore IS NULL) AS missing_rows,
   ROUND(COUNTIF(cagr_5_zscore IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'cagr_10_zscore' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(cagr_10_zscore IS NULL) AS missing_rows,
   ROUND(COUNTIF(cagr_10_zscore IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'returns_1' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(returns_1 IS NULL) AS missing_rows,
   ROUND(COUNTIF(returns_1 IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'returns_5' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(returns_5 IS NULL) AS missing_rows,
   ROUND(COUNTIF(returns_5 IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'returns_10' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(returns_10 IS NULL) AS missing_rows,
   ROUND(COUNTIF(returns_10 IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'beta' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(beta IS NULL) AS missing_rows,
   ROUND(COUNTIF(beta IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'beta_zscore' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(beta_zscore IS NULL) AS missing_rows,
   ROUND(COUNTIF(beta_zscore IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'm2' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(m2 IS NULL) AS missing_rows,
   ROUND(COUNTIF(m2 IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'm2_zscore' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(m2_zscore IS NULL) AS missing_rows,
   ROUND(COUNTIF(m2_zscore IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'sharpe' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(sharpe IS NULL) AS missing_rows,
   ROUND(COUNTIF(sharpe IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'sharpe_zscore' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(sharpe_zscore IS NULL) AS missing_rows,
   ROUND(COUNTIF(sharpe_zscore IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'returns_12mo_f' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(returns_12mo_f IS NULL) AS missing_rows,
   ROUND(COUNTIF(returns_12mo_f IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'returns_24mo_f' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(returns_24mo_f IS NULL) AS missing_rows,
   ROUND(COUNTIF(returns_24mo_f IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'returns_36mo_f' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(returns_36mo_f IS NULL) AS missing_rows,
   ROUND(COUNTIF(returns_36mo_f IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'cagr_12mo_f' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(cagr_12mo_f IS NULL) AS missing_rows,
   ROUND(COUNTIF(cagr_12mo_f IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'cagr_24mo_f' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(cagr_24mo_f IS NULL) AS missing_rows,
   ROUND(COUNTIF(cagr_24mo_f IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

UNION ALL

SELECT
   'cagr_36mo_f' AS columnname,
   COUNT(*) AS total_rows,
   COUNTIF(cagr_36mo_f IS NULL) AS missing_rows,
   ROUND(COUNTIF(cagr_36mo_f IS NULL)*100/COUNT(*),2) AS missing_percentage
FROM ${ref(constants.MS_TABLE)}
HAVING missing_percentage >25

