config {
  type: "table",
  schema: "dataform_staging",
  name: "5_check_duplicate_state_ts",
  tags: "requete8_5"
}


SELECT 
state,
month,
hpi_value,
hpi_yoy_pct_chg,
hpi_distance,
hpi_returns,
hpi_real,
hpi_trend,
afford_detrended,
afford_pmt,
acceleration_value,
velocity_value,
COUNT(*) as count
FROM ${ref('4_replace_table_state_ts')}
GROUP BY 
state,
month,
hpi_value,
hpi_yoy_pct_chg,
hpi_distance,
hpi_returns,
hpi_real,
hpi_trend,
afford_detrended,
afford_pmt,
acceleration_value,
velocity_value
HAVING count > 1
