config {
  type: "table",
  schema: "dataform_staging",
  name: "6_Clean_state_ts",
  tags: "requete8_6"
}
SELECT state, month, hpi_value, hpi_yoy_pct_chg, hpi_distance, hpi_returns, hpi_real, hpi_trend, afford_detrended, afford_pmt, acceleration_value, velocity_value
FROM (
  SELECT *, ROW_NUMBER() OVER(PARTITION BY state, month, hpi_value, hpi_yoy_pct_chg, hpi_distance, hpi_returns, hpi_real, hpi_trend, afford_detrended, afford_pmt, acceleration_value, velocity_value ORDER BY state) AS row_number
  FROM ${ref('4_replace_table_state_ts')}
)
WHERE row_number = 1
