config {
  
    type: "table",
    schema: "dataform_sources",
  }

SELECT
  date,
  country,
  hospitalized_patients_symptoms,
  hospitalized_patients_intensive_care,
  total_hospitalized_patients,
  home_confinement_cases,
  total_current_confirmed_cases,
  new_current_confirmed_cases,
  new_total_confirmed_cases,
  recovered,
  deaths,
  total_confirmed_cases,
  tests_performed,
  note
FROM ${ref(constants.NT_TABLE)}